// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_NCWWu9jm56NgJdo0fVGzHj4Kak2otXI',
    appId: '1:696570686436:web:fac55f989c56aa8c9cb5f1',
    messagingSenderId: '696570686436',
    projectId: 'synergy-f8235',
    authDomain: 'synergy-f8235.firebaseapp.com',
    storageBucket: 'synergy-f8235.appspot.com',
    measurementId: 'G-BMTS9JJ6YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEaMDFoNq8ygc8YYKMhYRsGmLHVJ02qU',
    appId: '1:696570686436:android:b3d12e98a41a90ec9cb5f1',
    messagingSenderId: '696570686436',
    projectId: 'synergy-f8235',
    storageBucket: 'synergy-f8235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KpbWAkdsrhrX43CLd4m01HNJRGz56sc',
    appId: '1:696570686436:ios:93039da7de71cbe49cb5f1',
    messagingSenderId: '696570686436',
    projectId: 'synergy-f8235',
    storageBucket: 'synergy-f8235.appspot.com',
    iosClientId: '696570686436-g4u34ec36al91ru606pp2knv5aoo03nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.synergy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7KpbWAkdsrhrX43CLd4m01HNJRGz56sc',
    appId: '1:696570686436:ios:93039da7de71cbe49cb5f1',
    messagingSenderId: '696570686436',
    projectId: 'synergy-f8235',
    storageBucket: 'synergy-f8235.appspot.com',
    iosClientId: '696570686436-g4u34ec36al91ru606pp2knv5aoo03nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.synergy',
  );
}
